### ISSUE TITLE
Amazon renamed some selectors

### ISSUE THREAD

**Issue by jamtur01** [Disane87/docudigger#4]
Currently fails with (on US Amazon):

```
TimeoutError: Waiting for selector `.pagination-full ul.a-pagination li:nth-last-child(2) a` failed: Waiting failed: 30000ms exceeded
```

**Comment by Disane87** [comment]
Yeah that could be possible. Only had the chance to test this with German Amazon. 

Do you have the chance to investigate it? Actually I'm pretty busy with family stuff.

**Comment by Disane87** [comment]
@jamtur01 I've tried to investigate this, but I had to cancel this because I have no orders on amazon.com, even when I can login with my de account.

**Comment by Disane87** [comment]
Do you have any updates on this @jamtur01?

I gonna stale this until further information

**Comment by jamtur01** [comment]
Sorry, I never got a chance to look back at this, life, etc. :)

**Comment by Disane87** [comment]
> Sorry, I never got a chance to look back at this, life, etc. :(

Yeah I really understand that, life is first priority. You can reopen it (or create antoher new issue) with more information when you've got some spare time.

Take care!
